import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Header from 'components/Header';
import Footer from 'components/Footer';
import {client} from "../libs/client";
import Category from 'components/Category';
import Author from 'components/Author';
import { useRouter } from 'next/router';
import BlogBox from 'components/BlogBox';




//ssg
export const getStaticProps = async() => {
  const data = await client.get({endpoint: "blog"});

  return {
    props: {
      blogs: data.contents,
      totalCount: data.totalCount
    },
  };
};




const inter = Inter({ subsets: ['latin'] })


export default function Home({blogs,totalCount}) {

  //クエリパラメーターがある場合はフィルターでそのカテゴリの記事だけ掲載する
    const router = useRouter();
    let test = {}
    let title =""
    let count = 1

    if (router.query.category != null){
      title = `${router.query.category}カテゴリの記事一覧`
      test = blogs.filter((blog) => {
        let cate = []
        blog.category.map((category) => {
          cate.push(category.name)
        })
        return cate.includes(router.query.category)
      })
      count = test.length
    } else { //クエリが無ければ全記事掲載
      test = blogs
      title = "全記事一覧"
      count = totalCount
    }
  
  

  return (
    <div>
      <Head>
        <title>SITENAME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>        
      {/* 左サイド */}
        <div  className={styles.mainLeft}>
          <h1>{title}</h1>
          <BlogBox blogs={test} totalCount={count} visible={false}/>
        </div>


      {/* 右サイド */}
        <div className={styles.mainRight}>
          <Category blogs={blogs}/>
          <Author/>
        </div>
      </main>

      <Footer/>
    </div>
  )
}
