import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Header from 'components/Header';
import Footer from 'components/Footer';
import {client} from "../libs/client";
import Category from 'components/Category';
import Author from 'components/Author';
import ProductList from 'components/ProductList';
import BlogBox from 'components/BlogBox';

//SSG
export const getStaticProps = async() => {
  const data = await client.get({endpoint: "blog"});
  return {
    props: {
      blogs: data.contents,
      totalCount: data.totalCount
    },
  };
};


const inter = Inter({ subsets: ['latin'] })


export default function Home({blogs,totalCount}) {
  return (
    <div>
      <Head>
        <title>SITENAME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />
      <main className={styles.main}>
        
        
    {/* 左サイド */}

        <div  className={styles.mainLeft}>
          <ProductList/>
          <BlogBox blogs={blogs} totalCount={totalCount} visible={true}/>
        </div>


    {/* 右サイド */}
        <div className={styles.mainRight}>
          <Category blogs={blogs}/>
          <Author/>
        </div>



      </main>

      <Footer/>
    </div>
  )
}
